import { seniorDevSessions } from "./seniorDev_start_mode.js";

/**
 * Break down the code changes into a step-by-step tutorial, grouped by the selected skills.
 * This tool takes a sessionId and (optionally) selectedSkills, generates a tutorial plan, and stores it in the session.
 *
 * Input: { sessionId: string, selectedSkills?: string[] }
 * Output: { content: [...], tutorialPlan: any }
 */
export async function seniorDev_generate_tutorial({ sessionId, selectedSkills }: { sessionId: string; selectedSkills?: string[] }) {
  const session = seniorDevSessions[sessionId];
  if (!session) {
    return {
      content: [
        { type: "text" as const, text: `❌ No session found for ID: ${sessionId}` },
      ],
      tutorialPlan: null,
    };
  }
  // Use selectedSkills from input or session
  const skills = selectedSkills && selectedSkills.length ? selectedSkills : session.selectedSkills || [];
  // Build each step as a TutorialStep for code reuse
  const steps = (skills as string[]).map((skill: string, i: number) => {
    // Find all files in the diff for this skill
    const relatedDiffs = Object.entries(session.diffs)
      .filter(([file, diff]: [string, unknown]) => typeof diff === "string" && diff.toLowerCase().includes(skill.toLowerCase()))
      .map(([file, diff]: [string, unknown]) => ({ file, diff }));
    // Compose a generic explanation and task
    const title = `Skill: ${skill}`;
    const explanation = `This step focuses on the code changes related to "${skill}". Review how this skill is applied in the codebase and understand its impact.`;
    const task = `Refactor or implement the code to demonstrate your understanding of "${skill}". Ensure the code is clean, idiomatic, and leverages best practices for this concept.`;
    return {
      stepNumber: i + 1,
      title,
      explanation,
      codeExample: undefined, // Could be generated by LLM in future
      task,
      validation: {
        type: "code-contains",
        checks: [skill],
      },
      diff: relatedDiffs,
    };
  });
  // Fallback: if no skills, just one step for all changes
  if (!steps.length) {
    steps.push({
      stepNumber: 1,
      title: "Skill: code change",
      explanation: "This step focuses on reviewing all code changes.",
      codeExample: undefined,
      task: "Review and refactor the code changes as needed.",
      validation: {
        type: "code-contains",
        checks: ["code change"],
      },
      diff: Object.entries(session.diffs).map(([file, diff]) => ({ file, diff })),
    });
  }
  const tutorialPlan = {
    sessionId,
    skills,
    steps,
    createdAt: new Date().toISOString(),
  };
  session.tutorialPlan = tutorialPlan;
  return {
    content: [
      { type: "text" as const, text: `Tutorial plan generated with ${steps.length} step(s).` },
    ],
    tutorialPlan,
  };
}
